"""Generate a Cypher script from a GraphModel.

Emits Neo4j 5-compatible Cypher:
  - Idempotent named uniqueness constraint.
  - Explicit per-property SET (avoids `SET a += {...}` map-merge quirks).
  - MERGE on the id property for idempotent node/edge creation.

Load via:
    cat dependency-graph.cypher | mgconsole <db>
  or the Neo4j Browser query box.
"""

from __future__ import annotations

from graph_model import GraphModel


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def export_cypher(model: GraphModel) -> str:
    lines: list[str] = []
    lines.append("// Auto-generated by projectgraph (Neo4j 5 compatible)")
    lines.append(
        "CREATE CONSTRAINT artifact_id_unique IF NOT EXISTS "
        "FOR (a:Artifact) REQUIRE a.id IS UNIQUE;"
    )
    lines.append("")

    # Nodes: unique by id (groupId:artifactId:version)
    for art in model.all_artifacts():
        nid = _esc(art["id"])
        lines.append(
            f"MERGE (a:Artifact {{id: '{nid}'}}) "
            f"SET a.groupId = '{_esc(art['groupId'])}', "
            f"a.artifactId = '{_esc(art['artifactId'])}', "
            f"a.version = '{_esc(art['version'])}', "
            f"a.packaging = '{_esc(art.get('packaging', 'jar'))}', "
            f"a.scope = '{_esc(art['scope'])}';"
        )

    lines.append("")
    # Edges
    seen_edges: set[tuple[str, str, str, str]] = set()
    for e in model.all_edges():
        edge_key = (
            e['from_id'], e['to_id'], e.get('scope', 'compile'),
            e.get('module_id', ''),
        )
        if edge_key in seen_edges:
            continue
        seen_edges.add(edge_key)
        lines.append(
            f"MATCH (s:Artifact {{id: '{_esc(e['from_id'])}'}}), "
            f"(t:Artifact {{id: '{_esc(e['to_id'])}'}}) "
            f"MERGE (s)-[:DEPENDS_ON {{"
            f"scope: '{_esc(e['scope'])}', "
            f"moduleId: '{_esc(e.get('module_id', ''))}', "
            f"depth: {int(e.get('depth', 0))}, "
            f"direct: {str(bool(e.get('direct', False))).lower()}"
            f"}}]->(t);"
        )

    return "\n".join(lines) + "\n"
