"""Generate a Cypher script from a GraphModel.

Emits Memgraph-compatible Cypher (also valid in Neo4j 5+):
  - Memgraph constraint syntax: `CREATE CONSTRAINT ON (n:Label) ASSERT n.prop IS UNIQUE;`
  - Explicit per-property SET (avoids `SET a += {...}` map-merge quirks).
  - MERGE on the id property for idempotent node/edge creation.

Load via:
    cat dependency-graph.cypher | mgconsole <db>
  or the Memgraph Lab / Neo4j Browser query box.
"""

from __future__ import annotations

from graph_model import GraphModel


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def export_cypher(model: GraphModel) -> str:
    lines: list[str] = []
    lines.append("// Auto-generated by projectgraph (Memgraph-compatible)")
    # Memgraph constraint syntax (also accepted by Neo4j for older syntax).
    # Wrapped in a try-safe form: if the constraint already exists it errors,
    # so use the IF NOT EXISTS guard Memgraph supports.
    lines.append("CREATE CONSTRAINT ON (a:Artifact) ASSERT a.id IS UNIQUE;")
    lines.append("")

    # Nodes: unique by id (groupId:artifactId:version)
    for art in model.all_artifacts():
        nid = _esc(art["id"])
        lines.append(
            f"MERGE (a:Artifact {{id: '{nid}'}}) "
            f"SET a.groupId = '{_esc(art['groupId'])}', "
            f"a.artifactId = '{_esc(art['artifactId'])}', "
            f"a.version = '{_esc(art['version'])}', "
            f"a.packaging = '{_esc(art.get('packaging', 'jar'))}', "
            f"a.scope = '{_esc(art['scope'])}';"
        )

    lines.append("")
    # Edges
    for e in model.all_edges():
        lines.append(
            f"MATCH (s:Artifact {{id: '{_esc(e['from_id'])}'}}), "
            f"(t:Artifact {{id: '{_esc(e['to_id'])}'}}) "
            f"MERGE (s)-[:DEPENDS_ON {{scope: '{_esc(e['scope'])}'}}]->(t);"
        )

    return "\n".join(lines) + "\n"
